FROM mcr.microsoft.com/devcontainers/python:3.11

# Instalar dependencias de sistema para OpenCV y Node.js
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    curl \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

# Instalar dependencias de Python globales
COPY requirements.txt /tmp/pip-tmp/
RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
    && rm -rf /tmp/pip-tmp